# coding: utf-8
"""
Django settings for base_sys_api_dj project.

Generated by 'django-admin startproject' using Django 1.11rc1.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""
import os
import json
import logging

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# 读取数据库配置文件
config_file = os.path.join(BASE_DIR, '.env')
with open(config_file) as f:
    config = f.read()
    DATABASES_CONFIG = json.loads(config)

DB_ENGINE = 'django.db.backends.mysql'
DB_WAIT_TIMEOUT = 29  # 单个连接最长维持时间
DB_POOL_SIZE = 8  # 连接池最大连接数

DATABASES = {
    'default': {
        'ENGINE': DB_ENGINE,
        'NAME': 'hdkt',
        'USER': DATABASES_CONFIG["HDKT_USER"],
        'PASSWORD': DATABASES_CONFIG["HDKT_PASSWORD"],
        'HOST': DATABASES_CONFIG["HDKT_HOST"],
        'PORT': DATABASES_CONFIG["HDKT_PORT"],
    },
    "tbkt_yw": {
        'ENGINE': DB_ENGINE,
        'NAME': 'tbkt_yw',
        'USER': DATABASES_CONFIG["YUWEN_SOURCE_USER"],
        'PASSWORD': DATABASES_CONFIG["YUWEN_SOURCE_PASSWORD"],
        'HOST': DATABASES_CONFIG["YUWEN_SOURCE_HOST"],
        'PORT': DATABASES_CONFIG["YUWEN_SOURCE_PORT"]
    },
    "ziyuan_new": {
        'ENGINE': DB_ENGINE,
        'NAME': 'ziyuan_new',
        'USER': DATABASES_CONFIG["SHUYING_SOURCE_USER"],
        'PASSWORD': DATABASES_CONFIG["SHUYING_SOURCE_PASSWORD"],
        'HOST': DATABASES_CONFIG["SHUYING_SOURCE_HOST"],
        'PORT': DATABASES_CONFIG["SHUYING_SOURCE_PORT"]
    },
    "ziyuan_yy": {
        'ENGINE': DB_ENGINE,
        'NAME': 'ziyuan_yy',
        'USER': DATABASES_CONFIG["SHUYING_SOURCE_USER"],
        'PASSWORD': DATABASES_CONFIG["SHUYING_SOURCE_PASSWORD"],
        'HOST': DATABASES_CONFIG["SHUYING_SOURCE_HOST"],
        'PORT': DATABASES_CONFIG["SHUYING_SOURCE_PORT"]
    }
}

TBKT_HOST = ""
FILE_VIEW_URL = DATABASES_CONFIG["FILE_VIEW_URL"]
FILE_CDN_URLROOT = DATABASES_CONFIG["FILE_VIEW_URL"]
# FILE_MEDIA_URLROOT = DATABASES_CONFIG["FILE_MEDIA_URLROOT"]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/dev/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '240897'

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True if DATABASES_CONFIG['DEBUG'] == "True" else False

ALLOWED_HOSTS = ['*']

# token cookies 属性
SESSION_COOKIE_NAME = "tbkt_token"
SESSION_COOKIE_AGE = 7 * 24 * 60 * 60
# SESSION_COOKIE_DOMAIN = DATABASES_CONFIG["ROOT_URL"]




INSTALLED_APPS = (
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # 'django.contrib.staticfiles',
    'libs.tags',

)




MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'hdkt_test.middleware.AuthenticationMiddleware',
)

ROOT_URLCONF = 'hdkt_test.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.jinja2.Jinja2',
        'DIRS': [os.path.join(BASE_DIR, 'templates/')],
        'OPTIONS': {
            'environment': 'libs.tags.templatetags.jj2.Env'
        }
    },
]

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, "django_cache"),
        'TIMEOUT': 600,
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}

# 接口地址字典
API_URLROOT = {}
# SMS_API_URL = DATABASES_CONFIG["SMS_API_URL"]
PROJECT_KEY = 'base_sys_api_dj'  # 项目key生成api间密匙key

for k, v in DATABASES_CONFIG.items():
    if k.startswith('API_URL_'):
        try:
            alias = k[8:].lower()
            API_URLROOT[alias] = v
        except Exception as e:
            print(e)
            pass


PASSWORD_HASHERS = (
    'django.contrib.auth.hashers.SHA1PasswordHasher',  # Insecure Hashes
)

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Etc/GMT-8'

USE_I18N = True

USE_L10N = True


